### ISSUE TITLE
Naming convention for logging

### ISSUE THREAD

**Issue by mashayev** [gliderlabs/logspout#205]
Hi,

I didn't find any option to change the logs output to different  naming convention:
instead of : 

Jul 06 14:27:29 "POD" "POD-info":  2016/07/06 11:27:29 - message

to be (for example):

Jul 06 14:27:29 "service" "specific pod info"

**Comment by josegonzalez** [comment]
What logging are you talkiing about?

**Comment by mashayev** [comment]
For example:

service (a.k.a nginx) specific pod info (a.k.a worker.{{ index }}) -  stdout message.

**Comment by mashayev** [comment]
After sone investigation I figure it out:

In order to make the logs per you naming convention you can use this in your yaml file (or use docker native commands):

yaml example:

```
        env:
          - name: SYSLOG_TAG
            value: '{{ index .Container.Config.Labels "io.kubernetes.pod.namespace" }}[{{ index .Container.Config.Labels "io.kubernetes.pod.name" }}]'
          - name: SYSLOG_HOSTNAME
            value: '{{ index .Container.Config.Labels "io.kubernetes.container.name" }}'
```

One thing which is missing is the ENV variables support [add env vars on SYSLOG_TAG template.](https://github.com/gliderlabs/logspout/pull/182)

Hope it will be finished soon.
