### ISSUE TITLE
Missing Logspout logs for containers running with TTY enabled

### ISSUE THREAD

**Issue by nma** [gliderlabs/logspout#231]
Just setup a logspout to test it out. Love the ease of use of the tool!

Though I am running into issues with a certain docker-compose v1 template.

```
serviceA:
  image: org/serviceA
  log_driver: 'json-file'
  log_opt:
    max-file: '1'
    max-size: '2M'
```

I noticed in my graylog setup that logspout is not sending any logging details for this service.
When I remove my custom _log_driver_ and _log_opt_ the problem is still not fixed. 

The only way for me to get logspout extracting details from the container of serviceA is when I run it outside of docker-compose.

```
docker run org/serviceA
```

So I am curious as to why some containers in a docker-compose does not get picked up by logspout? Is this a known issue?
