### ISSUE TITLE
Inconsistentcy of logs from v3.2+

### ISSUE THREAD

**Issue by iam404** [gliderlabs/logspout#312]
Some strange issue since upgrade to v3.2 or latest version. We are using logspout with kubernetes daemonset and logstash. Recently we realized logstash was not sending complete logs of container and this issue linked with recent version of logspout. Like if "helloworld" container printed 100 lines of "hello world" then logspout would fetch only 23-40 logs at max.

Luckily downgrading logspout version to v3 seems to have resolved the issue (with >1% error).

Logspout k8 configuration:
```
      containers:
      - image: gliderlabs/logspout:v3
        name: logspout
        args: ["syslog://localhost:5000"]

        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
```
