### ISSUE TITLE
unix /var/run/docker.sock: connect: permission denied

### ISSUE THREAD

**Issue by Ashtonian** [gliderlabs/logspout#316]
trying to run logspout with a custom adapter named `influx`. The adapter seems to be working fine but the container stops and logs `"pump ended: Get http://unix.sock/containers/json?: dial unix /var/run/docker.sock: connect: permission denied"`. For a while I was getting binding issues with :80, not sure what that was about either because the image had access to port 80, modifying the port to 8000 worked for me.  

docker compose logspout section I'm using:
```yml
logspout:
    environment:
    - RETRY_STARTUP=true
    - DEBUG=true
    - PORT=8000
    privileged: true
    volumes:
    -  /var/run/docker.sock:/var/run/docker.sock
    image: mylogspoutimagebuiltyesterday:1ec2a8d0
    stdin_open: true
    tty: true
    links:
    - telegraf:telegraf 
    ports:
    - 80:80/tcp
    - 8000:8000/tcp
    command:
    - influx://telegraf:9094 
    labels:
      io.rancher.container.pull_image: always
```
 
Full Log:
```
8/11/2017 5:39:52 PM# logspout 1 by gliderlabs
8/11/2017 5:39:52 PM# adapters: influx raw tcp tls udp
8/11/2017 5:39:52 PM# options : debug:true persist:/mnt/routes
8/11/2017 5:39:52 PM# jobs    : http[]:8000 pump routes
8/11/2017 5:39:52 PM# routes  :
8/11/2017 5:39:52 PM#   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
8/11/2017 5:39:52 PM#   influx	telegraf:9094	*_db			map[]
8/11/2017 5:39:52 PM2017/08/11 22:39:52 pump.Run(): using inactivity timeout:  0s
8/11/2017 5:39:52 PM2017/08/11 22:39:52 pump ended: Get http://unix.sock/containers/json?: dial unix /var/run/docker.sock: connect: permission denied
```

Modules in use:
```go
	_ "github.com/gliderlabs/logspout/transports/tcp"
	_ "github.com/gliderlabs/logspout/transports/tls"
	_ "github.com/gliderlabs/logspout/transports/udp"
	_ "github.com/meshifyiot/carbon-logspout/influx-adapter"
```

I run into this with rancher and os x
``` 
OS X: 10.13 Beta (17A330h) 
Docker: Docker version 17.06.0-ce 

Rancher | v1.6.0
Cattle | v0.179.7
```

I can post the adapter source if needed - its very simple, and pretty much the same as the logstash one just looks for a "METRIC" prefix keyword and ignores all the rest.
