### ISSUE TITLE
docker-compose please?

### ISSUE THREAD

**Issue by hanscees** [gliderlabs/logspout#344]
Hi,

has anyone written a docker-compose.yml file yet?

**Comment by hanscees** [comment]
sorry this should do it

##### docker-compose.yml
version: '3'
networks:
  logging:
services:
  logspout:
  image: gliderlabs/logspout:latest
  networks:
    - logging
  volumes:
    - /etc/hostname:/etc/host_hostname:ro
    - /var/run/docker.sock:/var/run/docker.sock
  command:
    syslog://192.168.0.61:514
  restart: always

################

**Comment by pitpit** [comment]
If someone needs it, here's a working version of docker-compose.yml for Docker Swarm:
```
version: '3.3'
services:
  logspout:
    image: gliderlabs/logspout
    command: syslog+tls://xxx.papertrailapp.com:xxx
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
```

> You need to replace `syslog+tls://xxx.papertrailapp.com:xxx` with the right command
