### ISSUE TITLE
Can't route to external logstash

### ISSUE THREAD

**Issue by tobiasfielitz** [gliderlabs/logspout#358]
We are running a staging stack and a logstash service outside of that stack. Logstash is accessible under `logstash-staging.<domain>:5000`.

How can I route the logs to my external ELK stack?

**docker-compose.yml**

```
  [..]
  logspout:
    image: bekt/logspout-logstash
    environment:
      ROUTE_URIS: 'logstash://logstash-staging.<domain>:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s
  [..]
```

`docker service logs staging_logspout` shows:

`!! bad adapter: logstash-staging.<domain>`
