### ISSUE TITLE
/etc/host_hostname not being read/used

### ISSUE THREAD

**Issue by mikeburgh** [gliderlabs/logspout#369]
Any advice on where to look to see why the /etc/host_hostname is not being picked up from the container in swarm mode ?

The configuration I am using is below. 
```yaml
logspout:
 image: gliderlabs/logspout:latest
    networks:
      - web
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      syslog+tls://.....
    read_only: true
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
```

I can see the host_hostname file is being mounted in the container: 
```
rw-r--r--    1 root     root            14 Dec 13 16:42 host_hostname
```
The contents of the file correctly show the host's hostname. 

The logs however always seem to have the containers hostname, unless I specify SYSLOG_HOSTNAME via an enviroment variable which does effectively change it.
