### ISSUE TITLE
"toJSON" not defined

### ISSUE THREAD

**Issue by zhaoyao91** [gliderlabs/logspout#395]
I just copy `{ "container" : "{{ .Container.Name }}", "labels": {{ toJSON .Container.Config.Labels }}, "timestamp": "{{ .Time.Format "2006-01-02T15:04:05Z07:00" }}", "source" : "{{ .Source }}", "message": {{ toJSON .Data }} }` from the README to my RAW_FORMAT env in compose file.

When I update the stack, it complains that toJSON not defined.

**Comment by zhaoyao91** [comment]
I then try to update it to just `{{.Data}}`, it complains 

```
Failure
failed to update service infra-log_logspout: Error response from daemon: rpc error: code = InvalidArgument desc = expanding env failed: expanding env "RAW_FORMAT={{.Data}}": template: expansion:1:2: executing "expansion" at <.Data>: can't evaluate field Data in type *template.Context
```

**Comment by zhaoyao91** [comment]
OK, I found the problem is about the compose file. For such  a compose file

```
version: "3.3"

services:
#  just-log:
#    image: zhaoyao91/just-log
#    environment:
#      INTERVAL: 10000
  logsout:
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LOGSPOUT: ignore
      ALLOW_TTY: "true"
#      RAW_FORMAT: "{{.Data}}\n"
      TEST: {{.Name}}
```

Docker seems to try to parse the `{{.Data}}` part which actually should not be parsed by docker and should be passed directly to logspout.

Does anybody know how to escape it?
