### ISSUE TITLE
Syslog: containers informations

### ISSUE THREAD

**Issue by sgrunt91** [gliderlabs/logspout#397]
Hello,

I want to put my containers logs into my syslog server (running with syslog-ng).
So I'm trying Logspout, and the logs are well sent on my syslog server.
But there only the stout of all containers, mixed il one log file. No container hostname or stack name (I'm using Rancher).
I would like to add some fields that are in my labels to the log line for identify what kind of log I have and do data extractions.

 Is it possible?

here is my actual config:
```

docker-compose.yml

version: '2'
services:
  logspout:
    image: gliderlabs/logspout:latest
    environment:
      LOGSPOUT: ignore
      ROUTE_URIS: udp://mysyslogserver:514
      SYSLOG_TAG: '{{ index .Container.Config.Labels "io.rancher.project_service.name"
        }}[{{ index .Container.Config.Labels "io.rancher.stack_service.name" }}]'
      SYSLOG_HOSTNAME: '{{ index .Container.Config.Labels "io.rancher.container.name"
        }}'
    stdin_open: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    ports:
    - 8086:80/tcp
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.hostname_override: container_name
```
But SYSLOG_TAG or SYSLOG_HOSTNAME don't change anything...
