### ISSUE TITLE
server hostname on which container is running in logs

### ISSUE THREAD

**Issue by mariaczi** [gliderlabs/logspout#450]
How we can grab the hostname of the server on which the container is runnig and send this hostname to the logs agregator: syslog-ng, logstash etc.?

Something we got when we use:
`docker service logs SERVICE|TASK`
And the output is:
```
node_app_1.7.zyp3bh58k6dn@SRVNAME     | app listening on port 80
node_app_1.7.zyp3bh58k6dn@SRVNAME     | queryDb took 35 ms ("select * from visits limit 1")
node_app_1.7.zyp3bh58k6dn@SRVNAME     | db error Error: read ECONNRESET
node_app_1.7.zyp3bh58k6dn@SRVNAME     |     at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {
node_app_1.7.zyp3bh58k6dn@SRVNAME     |   errno: 'ECONNRESET',
node_app_1.7.zyp3bh58k6dn@SRVNAME     |   code: 'ECONNRESET',
node_app_1.7.zyp3bh58k6dn@SRVNAME     |   syscall: 'read',
node_app_1.7.zyp3bh58k6dn@SRVNAME     |   fatal: true
node_app_1.7.zyp3bh58k6dn@SRVNAME     | }
node_app_1.7.zyp3bh58k6dn@SRVNAME     | /usr/src/app/src/db-mysql.js:139
node_app_1.7.zyp3bh58k6dn@SRVNAME     |         throw err;
node_app_1.7.zyp3bh58k6dn@SRVNAME     |         ^
node_app_1.7.zyp3bh58k6dn@SRVNAME     | 
node_app_1.7.zyp3bh58k6dn@SRVNAME     | Error: read ECONNRESET
node_app_1.7.zyp3bh58k6dn@SRVNAME     |     at TCP.onStreamRead (internal/stream_base_commons.js:201:27) {
node_app_1.7.zyp3bh58k6dn@SRVNAME     |   errno: 'ECONNRESET',
node_app_1.7.zyp3bh58k6dn@SRVNAME     |   code: 'ECONNRESET',
node_app_1.7.zyp3bh58k6dn@SRVNAME     |   syscall: 'read',
node_app_1.7.zyp3bh58k6dn@SRVNAME     |   fatal: true
node_app_1.7.zyp3bh58k6dn@SRVNAME     | }
```

**Comment by mariaczi** [comment]
OK. I'm able to have hostname on which the containter is running using environment variable for example:
```
-e "SYSLOG_HOSTNAME={{.Container.Config.Hostname}}@`hostname`"
```

**Comment by edorgeville** [comment]
You can also mount the host `/etc/hostname` inside the container as described in the README: https://github.com/gliderlabs/logspout#using-logspout-in-a-swarm

```
version: "3"
networks:
  logging:
services:
  logspout:
    image: gliderlabs/logspout:latest
    networks:
      - logging
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
```
