### ISSUE TITLE
Configuring syslog address via environment or configuration file

### ISSUE THREAD

**Issue by rarkins** [gliderlabs/logspout#90]
We use docker-compose, therefore the CMD for logspout is embedded in `docker-compose.yml`. However, the syslog addresses we use will be different _per environment_.

Can the syslog URI be provided at runtime in any way other than as a command line argument?

I'm also open to any other suggestions for how to have different destinations for production, staging, test, dev, etc.

**Comment by cweagans** [comment]
I'm also interested in this. Hoping to run Logspout on Dokku and I don't have any way to pass an argument to the end of the docker command.

**Comment by progrium** [comment]
Going to make it easier to add routes via environment. However, the routesapi lets you add them via HTTP, but that's far from ideal in your case.

**Comment by mmarcant** [comment]
+1 On this...
Is there a way to hack this now by modifiying $ROUTE_URIS or $ROUTE?

I'm trying to get logspout working in a kubernetes cluster.

**Comment by ardigo** [comment]
Also interested into being able to run logspout inside kubernetes. 
Has this been solved?

**Comment by markthom-as** [comment]
I was able to get it working on kubernetes, sending to papertrail with the following YAML:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logspout
  labels:
    tier: monitoring
    app: logspout
    version: v1
spec:
  template:
    metadata:
      labels:
        name: logspout
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          env:
            - name: SYSLOG_TAG
              value: '{{ index .Container.Config.Labels "io.kubernetes.pod.namespace" }}[{{ index .Container.Config.Labels "io.kubernetes.pod.name" }}]'
            - name: SYSLOG_HOSTNAME
              value: 'ENVIRONMENT_PREFIX-{{ index .Container.Config.Labels "io.kubernetes.container.name" }}'
            - name: ROUTE_URIS
              value: syslog+tls://logs.papertrailapp.com:YOUR_PORT
          image: gliderlabs/logspout
          name: logspout
          volumeMounts:
            - name: log
              mountPath: /var/run/docker.sock
      volumes:
        - name: log
          hostPath:
              path: /var/run/docker.sock
```
